/*
 * This source file was generated by the Gradle 'init' task
 */
package proj02;

public class App {
    public String getGreeting() {
        return "Hello World from project 02!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
