/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.test.java.javaproj01;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        app.src.main.java.javaproj01.App classUnderTest = new app.src.main.java.javaproj01.App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
